<?php

include 'conn.php';

// Get all appointments for calendar (current month and next month)
$calendar_start = date('Y-m-01');
$calendar_end = date('Y-m-t', strtotime('+1 month'));

$stmt = $conn->prepare("
    SELECT 
        a.date,
        a.time,
        a.purpose,
        a.status_enum,
        'resident' as type,
        u.name as resident_name
    FROM schedule s
    JOIN appointments a ON s.app_id = a.id
    JOIN users u ON a.user_id = u.id
    WHERE a.date BETWEEN ? AND ?
    AND a.status_enum IN ('approved', 'completed')
    
    UNION ALL
    
    SELECT 
        date,
        time,
        appointment_title as purpose,
        'scheduled' as status_enum,
        'mayor' as type,
        'Mayor' as resident_name
    FROM mayors_appointment
    WHERE date BETWEEN ? AND ?
    
    ORDER BY date ASC, time ASC
");
$stmt->bind_param("ssss", $calendar_start, $calendar_end, $calendar_start, $calendar_end);
$stmt->execute();
$result = $stmt->get_result();
$calendar_appointments = $result->fetch_all(MYSQLI_ASSOC);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar - Mayor Dashboard</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.0/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="dashboard-styles.css" rel="stylesheet">
</head>
<body>
    <!-- Sidebar -->
    <?php include 'sidebar.php'; ?>

    <!-- Main Content -->
    <div class="main-content" id="mainContent">
        <!-- Top Bar -->
        <?php include 'topbar.php'; ?>

        <!-- Content Area -->
        <div class="content-area">
            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">
                        <i class="bi bi-calendar-week"></i>
                        Calendar View
                    </h3>
                </div>
                <div class="card-body">
                    <div class="calendar-container">
                        <div class="calendar-header">
                            <div class="calendar-nav">
                                <button id="prevMonth">
                                    <i class="bi bi-chevron-left"></i>
                                </button>
                                <h4 class="calendar-title" id="calendarTitle"><?= date('F Y') ?></h4>
                                <button id="nextMonth">
                                    <i class="bi bi-chevron-right"></i>
                                </button>
                            </div>
                            <button class="btn btn-outline-primary btn-sm" id="todayBtn">Today</button>
                        </div>
                        <div class="calendar-grid" id="calendarGrid">
                            <!-- Day headers -->
                            <div class="calendar-day-header">Sun</div>
                            <div class="calendar-day-header">Mon</div>
                            <div class="calendar-day-header">Tue</div>
                            <div class="calendar-day-header">Wed</div>
                            <div class="calendar-day-header">Thu</div>
                            <div class="calendar-day-header">Fri</div>
                            <div class="calendar-day-header">Sat</div>
                            <!-- Calendar cells will be generated by JavaScript -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <script src="dashboard-scripts.js"></script>
    <script>
        // Calendar appointments data from PHP
        const calendarAppointments = <?= json_encode($calendar_appointments) ?>;
        let currentMonth = new Date().getMonth();
        let currentYear = new Date().getFullYear();

        document.addEventListener('DOMContentLoaded', function() {
            // Calendar functionality
            const prevMonthBtn = document.getElementById('prevMonth');
            const nextMonthBtn = document.getElementById('nextMonth');
            const todayBtn = document.getElementById('todayBtn');

            if (prevMonthBtn) {
                prevMonthBtn.addEventListener('click', function() {
                    currentMonth--;
                    if (currentMonth < 0) {
                        currentMonth = 11;
                        currentYear--;
                    }
                    generateCalendar();
                });
            }

            if (nextMonthBtn) {
                nextMonthBtn.addEventListener('click', function() {
                    currentMonth++;
                    if (currentMonth > 11) {
                        currentMonth = 0;
                        currentYear++;
                    }
                    generateCalendar();
                });
            }

            if (todayBtn) {
                todayBtn.addEventListener('click', function() {
                    const today = new Date();
                    currentMonth = today.getMonth();
                    currentYear = today.getFullYear();
                    generateCalendar();
                });
            }

            // Generate initial calendar
            generateCalendar();
        });

        function generateCalendar() {
            const calendarTitle = document.getElementById('calendarTitle');
            const calendarGrid = document.getElementById('calendarGrid');
            
            if (!calendarGrid) return;

            const monthNames = [
                'January', 'February', 'March', 'April', 'May', 'June',
                'July', 'August', 'September', 'October', 'November', 'December'
            ];

            // Update title
            if (calendarTitle) {
                calendarTitle.textContent = `${monthNames[currentMonth]} ${currentYear}`;
            }

            // Clear existing calendar cells (keep headers)
            const existingCells = calendarGrid.querySelectorAll('.calendar-cell');
            existingCells.forEach(cell => cell.remove());

            const firstDay = new Date(currentYear, currentMonth, 1);
            const lastDay = new Date(currentYear, currentMonth + 1, 0);
            const startDate = new Date(firstDay);
            startDate.setDate(startDate.getDate() - firstDay.getDay());

            const today = new Date();
            const todayString = today.toISOString().split('T')[0];

            for (let i = 0; i < 42; i++) {
                const cellDate = new Date(startDate);
                cellDate.setDate(startDate.getDate() + i);
                
                const cell = document.createElement('div');
                cell.className = 'calendar-cell';
                
                const isCurrentMonth = cellDate.getMonth() === currentMonth;
                const dateString = cellDate.toISOString().split('T')[0];
                
                if (!isCurrentMonth) {
                    cell.classList.add('other-month');
                }
                
                if (dateString === todayString) {
                    cell.classList.add('today');
                }

                // Day number
                const dayNumber = document.createElement('div');
                dayNumber.className = 'calendar-day-number';
                dayNumber.textContent = cellDate.getDate();
                cell.appendChild(dayNumber);

                // Add appointments for this date
                const dayAppointments = calendarAppointments.filter(apt => apt.date === dateString);
                dayAppointments.forEach(apt => {
                    const appointmentDiv = document.createElement('div');
                    appointmentDiv.className = `calendar-appointment ${apt.type}`;
                    appointmentDiv.textContent = `${apt.purpose.substring(0, 15)}${apt.purpose.length > 15 ? '...' : ''}`;
                    appointmentDiv.title = `${apt.purpose} - ${apt.time} (${apt.resident_name})`;
                    cell.appendChild(appointmentDiv);
                });

                calendarGrid.appendChild(cell);
            }
        }
    </script>
</body>
</html>